# GoReleaser configuration for LLM Proxy
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: llm_proxy
    binary: llm_proxy
    main: .
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    # Note: Cross-compilation with CGO (required for SQLite) is not supported
    # on standard GitHub Actions runners. This build only targets Linux x86_64.
    # Users on macOS, Windows, or ARM64 should build from source.
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      # Include documentation
      - README.md
      - LICENCE.md
      - DOCKER.md
      # Include config as config.toml (ready to use)
      - src: config.toml.example
        dst: config.toml
      # Include data directory with README
      - src: data/README
        dst: data/README
        strip_parent: false

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/stevelittlefish/llm_proxy:{{ .Tag }}"
      - "ghcr.io/stevelittlefish/llm_proxy:v{{ .Major }}"
      - "ghcr.io/stevelittlefish/llm_proxy:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/stevelittlefish/llm_proxy:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/stevelittlefish/llm_proxy"
      - "--label=org.opencontainers.image.description=LLM Proxy - Ollama-compatible API with multiple backend support"
      - "--label=org.opencontainers.image.licenses=MIT"

release:
  github:
    owner: stevelittlefish
    name: llm_proxy
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## LLM Proxy {{ .Tag }}
    
    ### Docker Images (Recommended)
    
    Pre-built Docker images are available on GitHub Container Registry:
    
    ```bash
    docker pull ghcr.io/stevelittlefish/llm_proxy:{{ .Tag }}
    ```
    
    See the [Quick Start with Docker](#quick-start-with-docker) section in the README for usage instructions.
    
    ### Pre-built Binary (Linux x86_64)
    
    Download the Linux x86_64 archive below.
    
    **Note:** Due to CGO requirements for SQLite, pre-built binaries are only available for Linux x86_64. 
    Users on macOS, Windows, or ARM64 should use Docker or build from source. See the README for build instructions.
    
    ### Installation
    
    1. Download the archive below
    2. Extract the archive
    3. Edit `config.toml` to configure your backend
    4. Run `./llm_proxy`
    
    See [README.md](https://github.com/stevelittlefish/llm_proxy/blob/main/README.md) for detailed documentation.
  footer: |
    **Full Changelog**: https://github.com/stevelittlefish/llm_proxy/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    Built with [GoReleaser](https://goreleaser.com/)

announce:
  skip: true
